name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.20

    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          | ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Build the application
      run: |
        go mod tidy
        go build -o hello-service .

    - name: Log in to DigitalOcean Container Registry
      run: echo "${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}" | docker login registry.digitalocean.com -u doctl --password-stdin

    - name: Build and tag the Docker image
      run: docker build -t registry.digitalocean.com/do-container/hello-service:${{ github.sha }} .

    - name: Push the Docker image
      run: docker push registry.digitalocean.com/do-container/hello-service:${{ github.sha }}

    - name: Deploy to Kubernetes
      env:
        KUBECONFIG: ${{ secrets.KUBECONFIG }}
      run: |
        kubectl set image deployment/hello-service hello-service=registry.digitalocean.com/do-container/hello-service:${{ github.sha }}
        kubectl rollout status deployment/hello-service
